name: Report a Bug
description: Use this template to report a bug.
title: "[Bug] "
labels: [ "bug" ]
body:
  - type: input
    id: title
    attributes:
      label: Bug Title
      description: Write a short, clear title for the bug.
      placeholder: A concise title for the bug
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Please provide a more detailed description of the bug.
      placeholder: Describe the bug in detail here.
    validations:
      required: true
