name: Request a New Language
description: Use this template for requesting a new language.
title: "[Langauge] Request New Language `<locale-code>`"
labels:
  - "new language"
body:
  - type: textarea
    id: title
    attributes:
      label: Language Request
      description: |
        Examples:
        - **Locale Code:** `zh_CN`
        - **English Name:** Simplified Chinese
        - **Native Name:** 简体中文
        - **Crowdin Code:** `zh-CN`
        - **ReadTheDocs Code:** `zh_CN`
      value: |
        - **Locale Code:**
        - **English Name:**
        - **Native Name:**
        - **Crowdin Code:**
        - **ReadTheDocs Code:**
    validations:
      required: true
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: The language is not requested yet.
          required: true
        - label: The language is available in [Language Table](https://github.com/ltdorgtest/lang-table).
