name: Request a New Version
description: Use this template for requesting a new version.
title: "[Version] Request New Version `<version>`"
labels:
  - "new version"
body:
  - type: textarea
    attributes:
      label: Version Request
      description: |
        Example 1:
        - **Version Name:** `4.0`
        - **Version Type:** `tag`

        Example 2:
        - **Version Name:** `master`
        - **Version Type:** `branch`
      value: |
        - **Version Name:**
        - **Version Type:**
    validations:
      required: true
