#
# Your Crowdin credentials.
#
project_id_env : CROWDIN_PROJECT_ID
api_token_env : CROWDIN_PERSONAL_TOKEN
base_path : "."
base_url_env : CROWDIN_BASE_URL

#
# Choose file structure in Crowdin.
#
preserve_hierarchy : true

#
# Use YAML anchor to implement the global languages mapping.
#
languages_mapping: &languages_mapping
  locale:
    zh-CN:  zh_CN
    zh-TW:  zh_TW

#
# Files configuration.
#
files:
  - source: /locale/pot/**/*.pot
    translation: /.crowdin/%locale%/**/%file_name%.po
    languages_mapping: *languages_mapping
